### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [ImperialCollegeLondon/RCDS-introduction-to-fortran#1]
I suggest adding the topic `fortran-tutorial` in the About section. There are a few other repos with that topic.

**Comment by cmcooling** [comment]
Sorry, I'm not experienced with tags. [This page](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags) suggests to me that tags are associated with releases and describe the release (so you might have a tag "v.1.0" for example), rather than the tag being associated with the repository as a whole. Or have I misunderstood your suggestion?

**Comment by Beliavsky** [comment]
I am not talking about a release tag. Topic tags appear in the About section as in my repo https://github.com/Beliavsky/FortranTip . How to add a topic is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by cmcooling** [comment]
Ah, I see, thank you for the clarification - I've not used that part of Github before. I added the tag as you suggested, thank you for the suggestion.
